{% set version = "1.0" %}
{% set name = "flintqs" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://files.sagemath.org/spkg/upstream/flintqs/{{ name }}-{{ version }}.tar.gz
  sha256: 7353dd18eae0f9c58ef405894a8987b1385012e60fea3d4aef2ebfccbacd97e7

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gmp
  run:
    - gmp

test:
  commands:
    - test -f $PREFIX/bin/QuadraticSieve

about:
  home: https://github.com/sagemath/FlintQS
  license: GPLv2+
  license_file: COPYING
  summary: William Hart's GPL'd Highly optimized multi-polynomial quadratic sieve for integer factorization
  dev_url: https://github.com/sagemath/FlintQS

extra:
  recipe-maintainers:
    - isuruf
