travis:
  secure:
    BINSTAR_TOKEN: AofG5rw0wE4Z/W7BWLDy5GrfTk6X/e1vO7gUGgBG1gh63ZHUi08M3TbGrmadvKKNoeFTS83x5/GgHUXeOXSWF+mhWWZ6OKfMOYkfOdjwHsJDAcqFSPMVzUiDkTfATXpiCYia9Xb1Q4cjlyG1pourtBQmHpnJ9jvIo4XmwMM1jp0KmExf/WodSJTMMhE9pu9X8cAX4QgV2y7cz5paGBr8PxfghC19HYmWL0KoR1fgdsRa3oPo89x8QJ4EAnv4/L1OPTLzRoZe1qeVjGEBv8wiOdLQD1A1YD39Ridri4+4oL2sORsX/ZOFqx+3I7oLK2gymqQHz/TPhqIThoOcClrsOhwnE1JIc6i2LGgzHatnXeUxGQSgZuqcq8TQccqV7ne1WndAlbGgzyRp299LcDdGY3XFfjV+9tv6eN3ZU6CR+opqt56TCMAy4vAd7PzYX/VFRcq1k0fRuljtFpdM3x/LlCJK/0Jb7FJosafOG1lodZ7daVr0mJRM5vrjWCUXeAqGYgQreuGbX0mvRh49g/elMdbr5g+Sw9/VYT3gBeT+nkY3SMyaOeDFHbqmegu1BDzPi5JMHq9sqMf/kySTgEkwd4J4iGYwrp8dqgkKKtoI4tYMHWr9Xt2rSPGgwYfXEPLj32etLXjoBMuTiB3jedSVs5ls9YLUvrk9xwwIDsziHyM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
